# Generated by Django 5.0.7 on 2024-07-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.etapa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.etapa')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='CostoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.etapa')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.material')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.tienda')),
            ],
        ),
    ]
