# Generated by Django 5.0.7 on 2024-08-19 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.clasificacion'),
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documentos_proyecto/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='fase',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.fase'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proveedor'),
        ),
    ]
