# Generated by Django 5.0.7 on 2024-08-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0002_clasificacion_proveedor_detallecompra_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='costohistorico',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='costohistorico',
            name='material',
        ),
        migrations.RemoveField(
            model_name='costohistorico',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='material',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='etapa',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.fase'),
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facturado', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.etapa')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.material')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.tienda')),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CostoHistorico',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
