# Generated by Django 5.0.7 on 2024-08-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0003_remove_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_contratista', models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], max_length=100)),
                ('especialidad', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255)),
                ('direccion', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usomaterial',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.CharField(max_length=255)),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_servicio', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.contratista')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.etapa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIBAASAPP.proyecto')),
            ],
        ),
    ]
