# Generated by Django 5.0.7 on 2024-08-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0005_categoria_descripcion_clasificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='en_proceso', max_length=20),
        ),
    ]
