# Generated by Django 5.0.7 on 2024-08-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0006_proyecto_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsoMaterial',
            new_name='Inventario',
        ),
    ]
