# Generated by Django 5.0.7 on 2024-08-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0007_rename_usomaterial_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='proyecto',
        ),
    ]
