# Generated by Django 5.0.7 on 2024-08-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0008_remove_fase_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5),
        ),
        migrations.AddField(
            model_name='inventario',
            name='iva',
            field=models.IntegerField(choices=[(8, '8%'), (16, '16%')], default=16, help_text='IVA en porcentaje'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
