# Generated by Django 5.0.7 on 2024-08-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0009_inventario_descuento_inventario_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='iva',
            field=models.PositiveIntegerField(choices=[(8, '8%'), (16, '16%')], default=16),
        ),
    ]
