# Generated by Django 5.0.7 on 2024-09-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBAASAPP', '0010_alter_inventario_descuento_alter_inventario_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='iva',
            field=models.PositiveIntegerField(choices=[(8, '8%'), (16, '16%')]),
        ),
    ]
